### ISSUE TITLE
Album and playlist API discussion

### ISSUE THREAD

**Issue by alex-nexus** [jmansor/ipsy-music#1]
what happens to songs when delete an album or a playlist?

**Comment by jmansor** [comment]
The way I've coded it, a song does not depend on a an artist or an album. This means that removing an artist or an album will not remove the songs related to them. Even more, because artists and albums may be related to a song, before you can remove either of them, you must remove first the relationship to the songs. 

I think in this case, we would need to use the ON DELETE SET NULL on the song references to albums and artists.
